name: deploy_to_page

on:
  push:
    branches:
      - main
      - page

jobs:
  build-and-deploy:
    permissions:
      pages: write
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: npm install -g @angular/cli
      - run: npm ci
      - run: ng lint
      - run: ng build --configuration production
      - name: Copy 404.html
        run: cp dist/kindnessally/browser/index.html dist/kindnessally/browser/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/kindnessally/browser
      - name: Deploy to Github pages
        uses: actions/deploy-pages@v4
